theme: jekyll-theme-minimal
title: Reality Master Test Pages
description: >- 
  just testing the GitHub Docs feature as a way for collaborative document editing.

  This content is located in the .yml file.

steps:

# 1
- title: main page
  description: testing yml link to main page.
  link: '{{ repoUrl }}/main'
